/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pemrograman_tugas_java_25;

/**
 *
 * @author 
 */
public class UserInterface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserInterface.class.getName());

    private java.awt.CardLayout cardLayout;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JList<String> classList;
    private javax.swing.DefaultListModel<String> classListModel;
    private javax.swing.JButton btnRun;
    private final String[] classNames = {"Calculator", "Data Mahasiswa", "Tugas", "Github"};
    private final String[] tugasNames = {
        "BangunRuang",
        "BubbleSortExample",
        "CekGenapGanjil",
        "FaktorialWhile",
        "KasirSederhana",
        "KonversiSuhu",
        "LuasPersegiPanjang",
        "Music",
        "NilaiHuruf",
        "RataRataNilai"
    };
    private final String[] tugasDeskripsi = {
        "BangunRuang: Program menghitung volume berbagai bangun ruang (kubus, balok, tabung, kerucut, limas, prisma, bola) menggunakan OOP.",
        "BubbleSortExample: Program mengurutkan array integer dengan algoritma Bubble Sort dan menampilkan hasilnya.",
        "CekGenapGanjil: Program untuk mengecek apakah sebuah bilangan yang diinput user adalah genap atau ganjil.",
        "FaktorialWhile: Program menghitung faktorial dari sebuah bilangan menggunakan perulangan while.",
        "KasirSederhana: Program kasir sederhana yang menghitung total harga, diskon, dan struk pembayaran.",
        "KonversiSuhu: Program konversi suhu dari Celsius ke Fahrenheit.",
        "LuasPersegiPanjang: Program menghitung luas persegi panjang berdasarkan input panjang dan lebar.",
        "Music: Program OOP polimorfisme untuk berbagai alat musik, menampilkan bunyi masing-masing alat musik.",
        "NilaiHuruf: Program mengubah nilai angka menjadi huruf mutu (A, B, C, D, E) sesuai rentang nilai.",
        "RataRataNilai: Program menghitung rata-rata dari 5 nilai tugas yang diinput user."
    };

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        cardLayout = new java.awt.CardLayout();
        mainPanel = new javax.swing.JPanel(cardLayout);

        // Kelas yang tersedia
        classListModel = new javax.swing.DefaultListModel<>();
        for (String name : classNames) classListModel.addElement(name);
        classList = new javax.swing.JList<>(classListModel);
        classList.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        classList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        classList.setSelectedIndex(0);
        javax.swing.JScrollPane classScroll = new javax.swing.JScrollPane(classList);
        javax.swing.JPanel leftPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        javax.swing.JLabel lblAvailable = new javax.swing.JLabel("Available Class");
        lblAvailable.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        lblAvailable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftPanel.add(lblAvailable, java.awt.BorderLayout.NORTH);
        leftPanel.add(classScroll, java.awt.BorderLayout.CENTER);

        // Tombol Run
        btnRun = new javax.swing.JButton("Run");
        btnRun.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        btnRun.addActionListener(e -> runSelectedClass());
        leftPanel.add(btnRun, java.awt.BorderLayout.SOUTH);

        // Panel kanan (CardLayout)
        rightPanel = new javax.swing.JPanel(cardLayout);
        rightPanel.add(new MenuPlaceholderPanel(), "menu");
        rightPanel.add(new CalculatorPanel(), "Calculator");
        rightPanel.add(new DataMahasiswaPanel(), "Data Mahasiswa");
        rightPanel.add(new TugasPanel(), "Tugas");
        rightPanel.add(new GithubPanel(), "Github");

        // SplitPane
        javax.swing.JSplitPane splitPane = new javax.swing.JSplitPane();
        splitPane.setLeftComponent(leftPanel);
        splitPane.setRightComponent(rightPanel);
        splitPane.setDividerLocation(180);
        splitPane.setResizeWeight(0.2);

        // Main panel
        mainPanel.setLayout(new java.awt.BorderLayout());
        mainPanel.add(splitPane, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setContentPane(mainPanel);
        setSize(1100, 800);
        setLocationRelativeTo(null);
        cardLayout.show(rightPanel, "menu");
    }// </editor-fold>//GEN-END:initComponents

    private void runSelectedClass() {
        String selected = classList.getSelectedValue();
        if (selected != null) {
            cardLayout.show(rightPanel, selected);
        }
    }

    // Placeholder panel untuk tampilan awal kanan
    private static class MenuPlaceholderPanel extends javax.swing.JPanel {
        public MenuPlaceholderPanel() {
            setLayout(new java.awt.GridBagLayout());
            javax.swing.JLabel label = new javax.swing.JLabel("Pilih kelas di kiri lalu klik Run");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.ITALIC, 18));
            add(label);
        }
    }

    // Custom panel for Calculator (reusing Calculator class as JPanel)
    private class CalculatorPanel extends javax.swing.JPanel {
        public CalculatorPanel() {
            setLayout(new java.awt.BorderLayout());
            javax.swing.JPanel headerPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
            javax.swing.JButton btnBack = new javax.swing.JButton("Back");
            btnBack.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
            btnBack.addActionListener(e -> cardLayout.show(rightPanel, "menu"));
            headerPanel.add(btnBack);
            add(headerPanel, java.awt.BorderLayout.NORTH);
            Calculator calc = new Calculator();
            add(calc.getContentPane(), java.awt.BorderLayout.CENTER);
        }
    }

    // Custom panel for Data Mahasiswa (reusing Data_Mahasiswa class as JPanel)
    private class DataMahasiswaPanel extends javax.swing.JPanel {
        public DataMahasiswaPanel() {
            setLayout(new java.awt.BorderLayout());
            javax.swing.JPanel headerPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
            javax.swing.JButton btnBack = new javax.swing.JButton("Back");
            btnBack.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
            btnBack.addActionListener(e -> cardLayout.show(rightPanel, "menu"));
            headerPanel.add(btnBack);
            add(headerPanel, java.awt.BorderLayout.NORTH);
            Data_Mahasiswa dataMhs = new Data_Mahasiswa();
            add(dataMhs.getContentPane(), java.awt.BorderLayout.CENTER);
        }
    }

    // Panel untuk Tugas
    private class TugasPanel extends javax.swing.JPanel {
        private javax.swing.JList<String> tugasList;
        private javax.swing.DefaultListModel<String> tugasListModel;
        private javax.swing.JTextArea detailArea;
        private javax.swing.JTextArea codeArea;

        public TugasPanel() {
            setLayout(new java.awt.BorderLayout(10, 10));
            javax.swing.JLabel lblTugas = new javax.swing.JLabel("Kumpulan Tugas");
            lblTugas.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            lblTugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            add(lblTugas, java.awt.BorderLayout.NORTH);
            tugasListModel = new javax.swing.DefaultListModel<>();
            for (String tugas : tugasNames) tugasListModel.addElement(tugas);
            tugasList = new javax.swing.JList<>(tugasListModel);
            tugasList.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
            tugasList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            javax.swing.JScrollPane tugasScroll = new javax.swing.JScrollPane(tugasList);
            add(tugasScroll, java.awt.BorderLayout.WEST);
            // Area detail
            detailArea = new javax.swing.JTextArea();
            detailArea.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
            detailArea.setEditable(false);
            detailArea.setLineWrap(true);
            detailArea.setWrapStyleWord(true);
            javax.swing.JScrollPane detailScroll = new javax.swing.JScrollPane(detailArea);
            // Area kode
            codeArea = new javax.swing.JTextArea();
            codeArea.setFont(new java.awt.Font("Consolas", java.awt.Font.PLAIN, 13));
            codeArea.setEditable(false);
            javax.swing.JScrollPane codeScroll = new javax.swing.JScrollPane(codeArea);
            // Panel tengah (detail 20% + kode 80%)
            javax.swing.JPanel centerPanel = new javax.swing.JPanel();
            centerPanel.setLayout(new java.awt.GridBagLayout());
            java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1.0;
            gbc.weighty = 0.2;
            gbc.fill = java.awt.GridBagConstraints.BOTH;
            centerPanel.add(detailScroll, gbc);
            gbc.gridy = 1;
            gbc.weighty = 0.8;
            centerPanel.add(codeScroll, gbc);
            add(centerPanel, java.awt.BorderLayout.CENTER);
            tugasList.addListSelectionListener(e -> showDetail());
        }
        private void showDetail() {
            String selected = tugasList.getSelectedValue();
            if (selected != null) {
                int idx = tugasList.getSelectedIndex();
                String deskripsi = (idx >= 0 && idx < tugasDeskripsi.length) ? tugasDeskripsi[idx] : "Deskripsi tidak tersedia.";
                detailArea.setText("File: " + selected + ".java\n\n" + deskripsi);
                codeArea.setText(readSourceCode(selected + ".java"));
            } else {
                detailArea.setText("");
                codeArea.setText("");
            }
        }
        private String readSourceCode(String filename) {
            StringBuilder sb = new StringBuilder();
            try {
                java.nio.file.Path path = java.nio.file.Paths.get("src/main/java/com/mycompany/pemrogramman", filename);
                java.util.List<String> lines = java.nio.file.Files.readAllLines(path);
                for (String line : lines) {
                    sb.append(line).append("\n");
                }
            } catch (Exception ex) {
                sb.append("Tidak bisa membaca kode: ").append(ex.getMessage());
            }
            return sb.toString();
        }
    }

    // Panel untuk Github
    private class GithubPanel extends javax.swing.JPanel {
        public GithubPanel() {
            setLayout(new java.awt.GridBagLayout());
            javax.swing.JLabel label = new javax.swing.JLabel("Kunjungi Github Saya:");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
            javax.swing.JButton btnLink = new javax.swing.JButton("Buka Github");
            btnLink.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
            btnLink.addActionListener(e -> {
                try {
                    java.awt.Desktop.getDesktop().browse(new java.net.URI("https://github.com/Cakraawala/pemrograman_tugas_java_25"));
                } catch (Exception ex) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka link: " + ex.getMessage());
                }
            });
            java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
            gbc.gridx = 0; gbc.gridy = 0; gbc.insets = new java.awt.Insets(10,10,10,10);
            add(label, gbc);
            gbc.gridy = 1;
            add(btnLink, gbc);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserInterface().setVisible(true));
    }

}
